//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentIndex
    {
        public byte id { get; set; }
        public string MainTableID { get; set; }
        public string LanguageID { get; set; }
        public string FormID { get; set; }
        public string TimeID { get; set; }
        public string PlaceID { get; set; }
        public string NationID { get; set; }
        public string PropertyID { get; set; }
    }
}
